apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
spec:
  type: NodePort
  selector:
    app: notes-api # Find all Pods with such label
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081

# type:
# ClusterIP - default type, creates an internal IP accessible only within the cluster
# NodePort - opens a port on each node to allow external access via <nodeIP>:<nodePort>
# LoadBalancer - provisions an external load balancer (in cloud environments) with a public IP
# ExternalName - maps the service to an external DNS name without proxy or IP
# Headless Service (clusterIP: None) - no cluster IP, returns pod IPs for direct access

