apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-api.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "notes-api.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{ include "notes-api.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}

# type:
# ClusterIP - default type, creates an internal IP accessible only within the cluster
# NodePort - opens a port on each node to allow external access via <nodeIP>:<nodePort>
# LoadBalancer - provisions an external load balancer (in cloud environments) with a public IP
# ExternalName - maps the service to an external DNS name without proxy or IP
# Headless Service (clusterIP: None) - no cluster IP, returns pod IPs for direct access

