apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres-db.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "postgres-db.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
